# file qish-gc/tools-dir/GNUmakefile
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2026 Basile STARYNKEVITCH, France
SUFFIXES += .i
RM=/bin/rm -vf
MV=/bin/mv
CP=/bin/cp -v
ED=/usr/bin/ed
CC?=/usr/bin/gcc
INDENT=/usr/bin/indent
INSTALL=/usr/bin/install
MKDIR=/usr/bin/mkdir -vp
RELEASE=1.0

.PHONY: all clean

